name: testing_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  orm: 4.0.0-beta.2
  material_design_icons_flutter: ^7.0.0
  flutter_hooks: ^0.20.4
  carousel_slider: ^4.2.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  url_launcher: ^6.2.4
  supabase_flutter: ^2.3.1
  supabase_auth_ui: ^0.4.1
  dotenv: ^4.2.0
  flutter_dotenv: ^5.1.0
  scrollable_positioned_list: ^0.3.8
  google_sign_in: ^6.2.1
  simple_icons: ^10.1.3
  neumorphic_button: ^0.0.1+2
  http: ^1.2.0
  flutter_map_marker_cluster: ^1.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
